# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: diamond-lang 1.2.1 ruby lib

Gem::Specification.new do |s|
  s.name = "diamond-lang"
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ben (@penne12_)"]
  s.date = "2016-01-02"
  s.description = "Making Minecraft 1 Command Creations with ruby. It's as easy as `c.say 123`"
  s.email = "ben@bensites.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "diamond-lang.gemspec",
    "examples/conveyor.rb",
    "examples/conveyor.txt",
    "examples/custom_crafting.rb",
    "examples/custom_crafting.txt",
    "examples/hello_world.rb",
    "examples/hello_world.txt",
    "examples/jetpack.rb",
    "examples/jetpack.txt",
    "lib/diamond-lang.rb",
    "lib/diamond-lang/command_chain.rb",
    "lib/diamond-lang/helpers/block.rb",
    "lib/diamond-lang/helpers/command.rb",
    "lib/diamond-lang/helpers/command_block.rb",
    "lib/diamond-lang/helpers/command_block_minecart.rb",
    "lib/diamond-lang/helpers/constants.rb",
    "lib/diamond-lang/helpers/coordinate.rb",
    "lib/diamond-lang/helpers/coordinates.rb",
    "lib/diamond-lang/helpers/custom_crafting.rb",
    "lib/diamond-lang/helpers/entity.rb",
    "lib/diamond-lang/helpers/errors/invalid_axis.rb",
    "lib/diamond-lang/helpers/errors/invalid_coordinate_value.rb",
    "lib/diamond-lang/helpers/errors/relative_cordinate_converted_to_argument.rb",
    "lib/diamond-lang/helpers/errors/too_small.rb",
    "lib/diamond-lang/helpers/falling_sand.rb",
    "lib/diamond-lang/helpers/target_selector.rb",
    "lib/diamond-lang/one_command.rb",
    "spec/errors/invalid_axis_spec.rb",
    "spec/errors/invalid_coordinate_value_spec.rb",
    "spec/errors/relative_cordinate_converted_to_argument_spec.rb",
    "spec/errors/too_small_spec.rb",
    "spec/helper.rb",
    "spec/helpers/block_spec.rb",
    "spec/index.html"
  ]
  s.homepage = "http://bensites.com/diamond-lang/"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "A Ruby Framework for creating Minecraft 1 Command Creations."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<require_all>, ["~> 1.3"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.11"])
      s.add_development_dependency(%q<rspec>, ["~> 3.4"])
      s.add_development_dependency(%q<pry>, ["~> 0.10"])
      s.add_development_dependency(%q<pry-doc>, ["~> 0.8"])
      s.add_development_dependency(%q<byebug>, ["~> 8.2"])
    else
      s.add_dependency(%q<require_all>, ["~> 1.3"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.11"])
      s.add_dependency(%q<rspec>, ["~> 3.4"])
      s.add_dependency(%q<pry>, ["~> 0.10"])
      s.add_dependency(%q<pry-doc>, ["~> 0.8"])
      s.add_dependency(%q<byebug>, ["~> 8.2"])
    end
  else
    s.add_dependency(%q<require_all>, ["~> 1.3"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.11"])
    s.add_dependency(%q<rspec>, ["~> 3.4"])
    s.add_dependency(%q<pry>, ["~> 0.10"])
    s.add_dependency(%q<pry-doc>, ["~> 0.8"])
    s.add_dependency(%q<byebug>, ["~> 8.2"])
  end
end

